export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const TOGGLE_SKILL_FORM = 'TOGGLE_SKILL_FORM';
export const TOGGLE_PROJECT_FORM = 'TOGGLE_PROJECT_FORM';
export const TOGGLE_JOB_FORM = 'TOGGLE_JOB_FORM';
export const TOGGLE_EDUCATION_FORM = 'TOGGLE_EDUCATION_FORM';